// <auto-generated />
namespace CompetentumWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedmanytomanyexperiencejob : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedmanytomanyexperiencejob));
        
        string IMigrationMetadata.Id
        {
            get { return "201707111226599_added many-to-many experience job"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
